### PR TITLE
CI: add clang builds

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
@felipeZ @JensWehner it seems clang+Debug takes over proportionally long.

**Comment by JensWehner** [comment]
This runs the tutorials as well?

**Comment by JensWehner** [comment]
any idea why?

**Comment by junghans** [comment]
It hangs in `QMMM_LAMMPS.ipynb`, so it isn't gromacs.

**Comment by JensWehner** [comment]
I think we should only run the tutorials in release mode.

**Comment by JensWehner** [comment]
they do some pretty heavy calculations for debug mode.

**Comment by junghans** [comment]
Well but on F32 both the clang-10, Release takes 8 min and Debug 2h 54min. 

Release is with `-O2` and Debug without optimization (`-O0`)  that might be it.

Should we disable the notebook generation with Debug? Or the whole spinx build?

**Comment by junghans** [comment]
Actually `-O3` for release, except Fedora changes CMake's default to `-O2`.

**Comment by JensWehner** [comment]
yes, no debug builds.

**Comment by junghans** [comment]
@jens: see https://github.com/votca/actions/pull/3

**Comment by junghans** [comment]
Downside of all that is that we won't get coverage reporting from the stuff ran in the tutorials.

**Comment by JensWehner** [comment]
Hmmm.... any options what we can do?

**Comment by junghans** [comment]
Shorter tests is the only options I see, that is basically what we do for csg-tutorials by setting the `CSG_MDRUN_STEPS` environment variable when running the tutorials as part of `make test`.  This is another things to change down road as currently the tutorials are ran by `make doc`, which is confusing at best.

**Comment by JensWehner** [comment]
yes that is true, concerning the length of the tests, we are as short as it can reasonably be.

**Pull request closed without merging**
