### PR TITLE
Update tutorial

### PR DESCRIPTION
**Pull request by felipeZ**
Synchonize tutorial with changes at master and adapt XML files to new [choices](https://github.com/votca/tools/issues/232) convention.

### CODE REVIEW

**Comment by JensWehner** [comment]
@felipeZ this is not uptodate for the latest changes, correct?

**Comment by felipeZ** [comment]
> @felipeZ this is not uptodate for the latest changes, correct?

Indeed it is not updated. I am running locally the tutorial and checking

**Comment by felipeZ** [comment]
@JensWehner this PR is ready for review

**Comment by felipeZ** [comment]
@JensWehner the `LAMMPS/Thiophene` tutorial is taking a lot of time and then  `segment faulting`:
```
./run.sh: line 107:   597 Segmentation fault      (core dumped) xtp_parallel -e iqm -o OPTIONFILES/iqm.xml -f state.hdf5 -s 0 -j run -c 1 -t 4
```
Could you please have  a look at the `run.sh` if you see something wrong?

**Comment by felipeZ** [comment]
The tutorial is broken after formating the xml files....

**Comment by felipeZ** [comment]
@JensWehner  the tutorial is now working

**Pull request merged**
